# Establece la imagen base utilizando una distribución de OpenJDK de Eclipse Temurin con Java 11
FROM eclipse-temurin:latest

# Actualiza los paquetes del sistema operativo dentro del contenedor
RUN apt-get update && apt-get -y upgrade

# Instala las herramientas inotify-tools y dos2unix en el contenedor
RUN apt-get install -y inotify-tools dos2unix

# Establece la variable de entorno HOME con el directorio /app
ENV HOME=/app

# Crea el directorio /app dentro del contenedor
RUN mkdir -p $HOME

# Establece el directorio de trabajo dentro del contenedor como /app
WORKDIR $HOME
