# Utiliza una imagen base con soporte para Java y Maven
FROM maven:3.8.3-openjdk-17-slim AS build

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo pom.xml y el archivo de configuración
COPY pom.xml .
COPY src ./src

# Construye el proyecto con Maven
RUN mvn package -DskipTests

# Segunda etapa para la imagen final
FROM openjdk:17-jdk-alpine

# Copia el artefacto construido en la etapa anterior
COPY --from=build /app/target/paymaven-0.0.1-SNAPSHOT.jar app.jar

# Expone el puerto en el que la aplicación escucha las solicitudes
EXPOSE 8080

# Comando para ejecutar la aplicación
CMD ["java", "-jar", "app.jar"]
